/* Generated By:JavaCC: Do not edit this line. TP1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TP1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int BOOL = 7;
  /** RegularExpression Id. */
  int IDENT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<NOMBRE>",
    "\";\"",
    "<FLOAT>",
    "<BOOL>",
    "<IDENT>",
    "\"===\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
  };

}
